name: Deploy Go Application on AWS

on:
  push:
    branches:
      - deployed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t dssanguano/go-deployment-aws .
      - name: Push image to docker hub
        run: docker push dssanguano/go-deployment-aws:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull dssanguano/go-deployment-aws:latest
      - name: Delete old container
        run: docker rm -f go-app-container  
      - name: Run docker container          
        run: docker run -d -p 4040:4040 --name go-app-container dssanguano/go-deployment-aws